import type { RecurringRule, RuleStatus, Transaction } from "./types";
import { isBeforeOrEqual, monthKey, pad2, type YearMonth } from "./month";

/** The amount effective for `ym`, or null if the rule hadn't started yet by that month. */
export function amountForMonth(rule: RecurringRule, ym: YearMonth): number | null {
  const applicable = rule.amountHistory
    .filter((e) => isBeforeOrEqual(e.effectiveFrom, ym))
    .sort((a, b) => (isBeforeOrEqual(a.effectiveFrom, b.effectiveFrom) ? -1 : 1));
  if (applicable.length === 0) return null;
  return applicable[applicable.length - 1].amount;
}

/** The status effective for `ym` ("active" if no events exist yet but history has started). */
export function statusForMonth(rule: RecurringRule, ym: YearMonth): RuleStatus {
  const applicable = rule.statusEvents
    .filter((e) => isBeforeOrEqual(e.effectiveFrom, ym))
    .sort((a, b) => (isBeforeOrEqual(a.effectiveFrom, b.effectiveFrom) ? -1 : 1));
  if (applicable.length === 0) return "active";
  return applicable[applicable.length - 1].status;
}

export function isActiveInMonth(rule: RecurringRule, ym: YearMonth): boolean {
  return amountForMonth(rule, ym) !== null && statusForMonth(rule, ym) === "active";
}

export function daysInMonth(ym: YearMonth): number {
  return new Date(ym.year, ym.month, 0).getDate();
}

export function dayForMonth(rule: RecurringRule, ym: YearMonth): number {
  return Math.min(rule.dayOfMonth, daysInMonth(ym));
}

/** The rule's current amount, as of "now" (latest history entry regardless of month). */
export function currentAmount(rule: RecurringRule): number | null {
  if (rule.amountHistory.length === 0) return null;
  const sorted = [...rule.amountHistory].sort((a, b) =>
    isBeforeOrEqual(a.effectiveFrom, b.effectiveFrom) ? -1 : 1
  );
  return sorted[sorted.length - 1].amount;
}

/** The rule's current status, as of "now" (latest status event). */
export function currentStatus(rule: RecurringRule): RuleStatus {
  if (rule.statusEvents.length === 0) return "active";
  const sorted = [...rule.statusEvents].sort((a, b) =>
    isBeforeOrEqual(a.effectiveFrom, b.effectiveFrom) ? -1 : 1
  );
  return sorted[sorted.length - 1].status;
}

/** Virtual transactions generated by all active rules for one month. Never persisted. */
export function generateRecurringTransactions(
  rules: RecurringRule[],
  ym: YearMonth
): Transaction[] {
  const result: Transaction[] = [];
  for (const rule of rules) {
    if (!isActiveInMonth(rule, ym)) continue;
    const amount = amountForMonth(rule, ym);
    if (amount === null) continue;
    const day = dayForMonth(rule, ym);
    result.push({
      id: `recurring:${rule.id}:${monthKey(ym)}`,
      date: `${ym.year}-${pad2(ym.month)}-${pad2(day)}`,
      type: rule.type,
      amount,
      category: rule.category,
      memo: rule.name,
      costType: rule.type === "expense" ? "fixed" : undefined,
      isRecurring: true,
      ruleId: rule.id,
    });
  }
  return result;
}

/** Manual transactions for the month plus every active rule's derived transaction, combined. */
export function getMonthTransactions(
  manualTransactions: Transaction[],
  rules: RecurringRule[],
  ym: YearMonth
): Transaction[] {
  const key = monthKey(ym);
  const manual = manualTransactions.filter((t) => t.date.startsWith(key));
  return [...generateRecurringTransactions(rules, ym), ...manual];
}
